security:
    encoders:
        App\Entity\Utilisateur:
            algorithm: md5
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthentificatorAuthenticator
            logout:
                path: app_logout
                target: app_home
    access_denied_url: /

    access_control:
        - { path: admin_home, roles: ROLE_ADMIN }
        - { path: user_home, roles: ROLE_USER }
